#!/usr/bin/env python3
"""
Apply arc-overhang post-processing to a Bambu Studio exported .3mf (single or multi-plate).

Pipeline per plate:
    Metadata/plate_N.gcode
        -> translate Bambu markers to OrcaSlicer markers
        -> run arc_overhangs_v1.0.0.py (post-processor)
        -> translate markers back to Bambu
        -> refresh plate_N.gcode.md5
Multiple plates are processed in parallel.

Usage:
    bambu_arc_overhang.py <input.3mf> [-o output.3mf] [knobs...]

Defaults (chosen for fast prints, tuneable below):
  - OnlyBridgesSupportingTopSurfaces=True: only bridges sitting beneath an unbroken
    stack of internal solid infill capped by a top surface become arcs.
  - ArcPrintSpeed=5 mm/s (upstream default is 1.5 mm/s; raise for faster, lower for safer
    bonding on overhang-prone material).
  - specialCoolingZdist=0: the "slow everything within 3 mm above each arc" cooling pass
    is OFF. Re-enable per-distance with --above-arcs-zdist.
  - applyAboveFanSpeedToWholeLayer=False: even if you re-enable the cooling pass, the
    fan boost is no longer forced across whole layers.
  - doSpecialCooling=False: Hilbert-curve cross-hatch over solid infill above arcs is OFF.
    Re-enable with --enable-hilbert-cooling (also requires --above-arcs-zdist > 0).
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
POST_PROCESSOR = SCRIPT_DIR / "arc_overhangs_v1.0.0.py"
VENV_PYTHON = SCRIPT_DIR / ".venv" / "bin" / "python"

BAMBU_TO_ORCA = [
    ("; CHANGE_LAYER", ";LAYER_CHANGE"),
    ("; WIPE_START", ";WIPE_START"),
    ("; WIPE_END", ";WIPE_END"),
]
ORCA_TO_BAMBU = [(b, a) for a, b in BAMBU_TO_ORCA]

FEATURE_RE = re.compile(r"^; FEATURE: (.+)$")
TYPE_RE = re.compile(r"^;TYPE:(.+)$")

# Type names the post-processor invents that Bambu Studio's gcode preview
# does not recognize. These get renamed to a known Bambu feature on the way
# back out so the preview parser categorizes them correctly. Without this,
# Bambu Studio wipes the plate when you select it (unrecognized FEATURE name
# breaks its preview rendering).
TYPE_NAME_REWRITES = {
    "Arc infill": "Bridge",
}


def bambu_to_orca(text: str) -> str:
    out_lines = []
    for line in text.splitlines(keepends=True):
        stripped = line.rstrip("\r\n")
        eol = line[len(stripped):]
        m = FEATURE_RE.match(stripped)
        if m:
            out_lines.append(f";TYPE:{m.group(1)}{eol}")
            continue
        replaced = stripped
        for src, dst in BAMBU_TO_ORCA:
            if replaced == src:
                replaced = dst
                break
        out_lines.append(replaced + eol)
    out = "".join(out_lines)
    if "; generated by OrcaSlicer" not in out:
        out = out.replace(
            "; HEADER_BLOCK_END",
            "; generated by OrcaSlicer 2.2.0 (BambuStudio compat shim)\n; HEADER_BLOCK_END",
            1,
        )
    return out


def orca_to_bambu(text: str) -> str:
    out_lines = []
    for line in text.splitlines(keepends=True):
        stripped = line.rstrip("\r\n")
        eol = line[len(stripped):]
        if stripped == "; generated by OrcaSlicer 2.2.0 (BambuStudio compat shim)":
            continue
        m = TYPE_RE.match(stripped)
        if m:
            name = TYPE_NAME_REWRITES.get(m.group(1), m.group(1))
            out_lines.append(f"; FEATURE: {name}{eol}")
            continue
        replaced = stripped
        for src, dst in ORCA_TO_BAMBU:
            if replaced == src:
                replaced = dst
                break
        out_lines.append(replaced + eol)
    return "".join(out_lines)


RUNNER_TEMPLATE = '''\
import runpy
ns = runpy.run_path({post_processor!r}, run_name="not_main")
_orig_make = ns["makeFullSettingDict"]
def _patched_make(gCodeSettingDict):
    full = _orig_make(gCodeSettingDict)
    full["OnlyBridgesSupportingTopSurfaces"] = True
    full["ReplaceInternalBridging"] = True
    {arc_print_speed_line}
    {arc_min_print_speed_line}
    full["MinTopSurfaceCoverageRatio"] = {min_top_coverage}
    full["MinFillRatioToReplace"] = {min_fill_ratio}
    full["BridgePolyClosingRadius"] = {bridge_closing_mm}
    {arc_center_offset_line}
    full["specialCoolingZdist"] = {special_cooling_zdist_mm}
    full["doSpecialCooling"] = {do_special_cooling}
    full["applyAboveFanSpeedToWholeLayer"] = {apply_fan_to_whole_layer}
    full["Path2Output"] = {out_path!r}
    return full
ns["main"].__globals__["makeFullSettingDict"] = _patched_make
stream, path = ns["getFileStreamAndPath"]({in_path!r})
ns["main"](stream, path)
'''


class Settings:
    """Tuning knobs forwarded to the post-processor."""

    def __init__(
        self,
        arc_speed_mm_s,  # float | None
        arc_min_speed_mm_s,  # float | None
        min_top_coverage: float,
        min_fill_ratio: float,
        bridge_closing_mm: float,
        arc_center_offset_mm,  # float | None
        above_arcs_zdist_mm: float,
        hilbert_cooling: bool,
        fan_boost_whole_layer: bool,
    ) -> None:
        self.arc_speed_mm_s = arc_speed_mm_s
        self.arc_min_speed_mm_s = arc_min_speed_mm_s
        self.min_top_coverage = min_top_coverage
        self.min_fill_ratio = min_fill_ratio
        self.bridge_closing_mm = bridge_closing_mm
        self.arc_center_offset_mm = arc_center_offset_mm
        self.above_arcs_zdist_mm = above_arcs_zdist_mm
        self.hilbert_cooling = hilbert_cooling
        self.fan_boost_whole_layer = fan_boost_whole_layer


def run_post_processor(in_path: Path, out_path: Path, settings: Settings) -> None:
    if not POST_PROCESSOR.exists():
        sys.exit(f"Post-processor not found at {POST_PROCESSOR}")
    if not VENV_PYTHON.exists():
        sys.exit(
            f"venv python not found at {VENV_PYTHON}. "
            f"Create it and install requirements.txt first."
        )

    if settings.arc_center_offset_mm is None:
        arc_center_offset_line = "pass  # arc-center-offset: use script default"
    else:
        arc_center_offset_line = f'full["ArcCenterOffset"] = {float(settings.arc_center_offset_mm)}'
    if settings.arc_speed_mm_s is None:
        arc_print_speed_line = "pass  # arc-speed: inherit from slicer's bridge_speed"
    else:
        arc_print_speed_line = f'full["ArcPrintSpeed"] = {float(settings.arc_speed_mm_s) * 60}'
    if settings.arc_min_speed_mm_s is None:
        arc_min_print_speed_line = "pass  # arc-min-speed: inherit from arc-speed (= bridge_speed by default)"
    else:
        arc_min_print_speed_line = f'full["ArcMinPrintSpeed"] = {float(settings.arc_min_speed_mm_s) * 60}'
    runner_src = RUNNER_TEMPLATE.format(
        post_processor=str(POST_PROCESSOR),
        in_path=str(in_path),
        out_path=str(out_path),
        arc_print_speed_line=arc_print_speed_line,
        arc_min_print_speed_line=arc_min_print_speed_line,
        min_top_coverage=settings.min_top_coverage,
        min_fill_ratio=settings.min_fill_ratio,
        bridge_closing_mm=settings.bridge_closing_mm,
        arc_center_offset_line=arc_center_offset_line,
        special_cooling_zdist_mm=settings.above_arcs_zdist_mm,
        do_special_cooling=repr(bool(settings.hilbert_cooling)),
        apply_fan_to_whole_layer=repr(bool(settings.fan_boost_whole_layer)),
    )
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
        f.write(runner_src)
        runner = f.name
    try:
        result = subprocess.run(
            [str(VENV_PYTHON), runner],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            sys.stdout.write(result.stdout)
            sys.stderr.write(result.stderr)
            raise RuntimeError(
                f"Post-processor failed with exit code {result.returncode} for {in_path.name}."
            )
        return result.stdout
    finally:
        os.unlink(runner)


def process_one_plate(
    gcode_path: Path, td_path: Path, settings: Settings
) -> tuple[str, float, bool, list[str]]:
    """Translate, run post-processor, translate back, refresh md5.

    Returns (label, secs, modified, coverage_lines).
    """
    label = gcode_path.relative_to(td_path).as_posix()
    t0 = time.perf_counter()

    original_text = gcode_path.read_text(encoding="utf-8")
    orca_text = bambu_to_orca(original_text)
    shim_in = td_path / (gcode_path.stem + "_orca_in.gcode")
    shim_out = td_path / (gcode_path.stem + "_orca_out.gcode")
    shim_in.write_text(orca_text, encoding="utf-8")

    coverage_lines: list[str] = []
    try:
        stdout = run_post_processor(shim_in, shim_out, settings)
        coverage_lines = [
            line
            for line in (stdout or "").splitlines()
            if line.startswith("Coverage:")
            or line.startswith("  Layers with")
            or line.startswith("    layer ")
            or "rejecting poly" in line
        ]

        modified = shim_out.exists() and shim_out.stat().st_size > 0
        if modified:
            modified_text = shim_out.read_text(encoding="utf-8")
            final_text = orca_to_bambu(modified_text)
            gcode_path.write_text(final_text, encoding="utf-8")

            md5_path = gcode_path.with_suffix(gcode_path.suffix + ".md5")
            new_md5 = hashlib.md5(final_text.encode("utf-8")).hexdigest().upper()
            md5_path.write_text(new_md5, encoding="utf-8")
    finally:
        shim_in.unlink(missing_ok=True)
        shim_out.unlink(missing_ok=True)

    return label, time.perf_counter() - t0, modified, coverage_lines


def process_3mf(in_3mf: Path, out_3mf: Path, settings: Settings, workers: int) -> None:
    if in_3mf.resolve() == out_3mf.resolve():
        sys.exit("Input and output paths must differ.")

    overall = time.perf_counter()
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        with zipfile.ZipFile(in_3mf, "r") as zin:
            zin.extractall(td_path)

        gcode_files = sorted(td_path.glob("Metadata/plate_*.gcode"))
        if not gcode_files:
            sys.exit("No Metadata/plate_*.gcode found in archive.")

        n = len(gcode_files)
        # Default (workers=None) = one worker per plate. Explicit --workers caps it.
        actual_workers = max(1, n if workers is None else min(workers, n))
        print(f"Processing {n} plate(s) with {actual_workers} worker(s)...")

        with ThreadPoolExecutor(max_workers=actual_workers) as ex:
            futures = {
                ex.submit(process_one_plate, p, td_path, settings): p for p in gcode_files
            }
            for fut in as_completed(futures):
                label, secs, modified, coverage_lines = fut.result()
                tag = "modified" if modified else "no qualifying bridges; unchanged"
                print(f"  [{secs:6.1f}s] {label}: {tag}")
                for cov_line in coverage_lines:
                    print(f"    {cov_line}")

        with zipfile.ZipFile(in_3mf, "r") as zin:
            entry_order = [info.filename for info in zin.infolist()]
            entry_compress = {info.filename: info.compress_type for info in zin.infolist()}

        with zipfile.ZipFile(out_3mf, "w") as zout:
            for name in entry_order:
                src = td_path / name
                if not src.exists():
                    continue
                zout.write(
                    src, name, compress_type=entry_compress.get(name, zipfile.ZIP_DEFLATED)
                )

    print(f"\nWrote: {out_3mf}  (total {time.perf_counter() - overall:.1f}s)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("input", type=Path, help="Path to input .3mf")
    parser.add_argument("-o", "--output", type=Path, default=None, help="Output .3mf path")
    parser.add_argument(
        "--arc-speed",
        type=float,
        default=None,
        help="Arc print speed in mm/s. If unset, falls back to the slicer's bridge_speed "
        "so tuning the bridge profile in Bambu Studio directly tunes the arcs (recommended). "
        "Pass an explicit value to override.",
    )
    parser.add_argument(
        "--arc-min-speed",
        type=float,
        default=None,
        help="Minimum arc print speed in mm/s for short arcs that the slowdown logic "
        "(ArcSlowDownBelowThisDuration=3s) would otherwise drop below. If unset, equals "
        "--arc-speed (i.e. no slowdown — arcs print at bridge_speed regardless of length). "
        "Set explicitly to enable per-arc slowdown for tiny radii.",
    )
    parser.add_argument(
        "--min-top-coverage",
        type=float,
        default=0.5,
        help="Minimum fraction (0..1) of the bridge's area that must be directly under "
        "solid material (Top surface or Internal solid infill) in the very next layer "
        "for the bridge to qualify for arc replacement. Filters out 'internal web' "
        "bridges that span over voids/sparse infill. Default 0.5; set to 0 to disable.",
    )
    parser.add_argument(
        "--arc-center-offset",
        type=float,
        default=None,
        help="Override the arc center offset in mm (upstream default 1.5*nozzle_diameter "
        "= 0.6 mm at 0.4 nozzle). Lower it (e.g. 0.2 or 0.0) to fill thin/long bridge "
        "sections that the BFS otherwise skips. Smaller values can reduce arc bonding "
        "quality on small radii. If unset, the upstream default is used.",
    )
    parser.add_argument(
        "--min-fill-ratio",
        type=float,
        default=0.0,
        help="If >0, reject any bridge whose BFS fills less than this fraction of its "
        "area (the bridge stays as bridge — no arcs, no deletion). Use this to avoid "
        "leaving thin sections unsupported. Try 0.85 if the coverage diagnostic shows "
        "significant unfilled area on a load-bearing layer. Default 0 = always replace.",
    )
    parser.add_argument(
        "--bridge-closing",
        type=float,
        default=1.0,
        help="Closing-operation radius in mm applied to bridge polygons before arc "
        "generation. Merges adjacent buffered gcode lines so the BFS sees the bridge's "
        "full surface independent of the slicer's infill direction (avoids 'comb' "
        "polygons with gaps between parallel bridge lines). Default 1.0; set to 0 to "
        "disable.",
    )
    parser.add_argument(
        "--above-arcs-zdist",
        type=float,
        default=0.0,
        help="mm of vertical distance above each arc region for the post-processor's "
        "above-arcs cooling pass (slow perimeters/infill near the arc footprint). "
        "Default 0 = OFF entirely. Upstream default is 3 mm (~15 layers of slowdown).",
    )
    parser.add_argument(
        "--enable-hilbert-cooling",
        action="store_true",
        help="Re-enable the Hilbert-curve cross-hatch pattern over internal solid infill "
        "above arcs. Requires --above-arcs-zdist > 0 to take effect. Off by default.",
    )
    parser.add_argument(
        "--fan-boost-whole-layer",
        action="store_true",
        help="If above-arcs cooling is on, force fan boost across the whole layer once "
        "any line is near an arc. Off by default.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=None,
        help="Max plates to process in parallel. Default = one worker per plate "
        "(every plate runs concurrently). Pass an integer to cap it.",
    )
    args = parser.parse_args()

    in_3mf: Path = args.input.expanduser()
    if not in_3mf.exists():
        sys.exit(f"Input not found: {in_3mf}")

    out_3mf: Path = args.output or in_3mf.with_name(in_3mf.stem + "_arc.3mf")

    settings = Settings(
        arc_speed_mm_s=args.arc_speed,
        arc_min_speed_mm_s=args.arc_min_speed,
        min_top_coverage=args.min_top_coverage,
        min_fill_ratio=args.min_fill_ratio,
        bridge_closing_mm=args.bridge_closing,
        arc_center_offset_mm=args.arc_center_offset,
        above_arcs_zdist_mm=args.above_arcs_zdist,
        hilbert_cooling=args.enable_hilbert_cooling,
        fan_boost_whole_layer=args.fan_boost_whole_layer,
    )
    process_3mf(in_3mf, out_3mf, settings, args.workers)


if __name__ == "__main__":
    main()
